### ISSUE TITLE
Expose envoy healthcheck endpoint on traffic port

### ISSUE THREAD

**Issue by haswalt** [saarasio/enroute#73]
External load balancers providers like AWS require a healthcheck in order for hosts to be enabled in the pool. Typically it is expected that a healthcheck is exposed by the target-port, usually this is a simple 200 or 204 response to `GET /`. However unless there is a specific route configured EnRoute / Envoy returns 404 for these checks resulting in hosts being removed from the pool.

Ideally to check the host status the Envoy healthcheck should be exposed, this can be achieved by adding an additional port mapping to Envoy (port `8000`):

```
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  - name: hc
    port: 8000
    protocol: TCP
    targetPort: 8000
```

However this exposes other Envoy endpoints to the public, EnRoute should include it's own healtcheck endpoint that either proxies or checks the Envoy status before return a `200`.
